<?php
$this->widget('ext.EExcelView', array(
            'dataProvider'=>$dataProvider
            ,'columns'=>array(
                array(
                    'name'=>'game_id',
                    'header'=>'游戏',
                    'type'=>'raw',
                    'value'=>'$data["game_name"]'
                    ),
                array(
                    'name'=>'server_id',
                    'header'=>'区服',
                    'type'=>'raw',
                    'value'=>'$data["server_name"]'
                    ),
                array(
                    'name'=>'open_time',
                    'header'=>'开服时间',
                    'type'=>'date',
                    'value'=>'$data["open_time"]'
                    ),
                array(
                    'name'=>'cost',
                    'header'=>'成本',
                    'type'=>'raw',
                    'value'=>'$data["cost"]'
                    ),
                array(
                        'name'=>'register',
                        'header'=>'注册',
                        'type'=>'raw',
                        'value'=>'$data["register"]'
                     ),
                array(
                        'name'=>'cpa',
                        'header'=>'cpa',
                        'type'=>'raw',
                        'value'=>'$data["cpa"]'
                     ),
                array(
                        'name'=>'revisit',
                        'header'=>'回访数',
                        'type'=>'raw',
                        'value'=>'$data["revisit"]'
                     ),
                array(
                        'header'=>'回访成本',
                        'type'=>'raw',
                        'value'=>'$data["revisit_cost"]'
                     ),
                array(
                        'header'=>'回访率',
                        'type'=>'raw',
                        'value'=>'$data["revisit_percent"]. "%"'
                     ),
                array(
                        'header'=>'充值率',
                        'type'=>'raw',
                        'value'=>'$data["payment_percent"]. "%"'
                     ),
                array(
                        'header'=>'充值额',
                        'type'=>'raw',
                        'value'=>'$data["payment"]'
                     ),
                array(
                        'header'=>'游戏充值',
                        'type'=>'raw',
                        'value'=>'$data["amount"]'
                     ),
                array(
                        'header'=>'分成利润',
                        'type'=>'raw',
                        'value'=>'$data["income"]'
                     ),
                array(
                        'name'=>'profit_percent',
                        'header'=>'回款率',
                        'type'=>'raw',
                        'value'=>'$data["profit_percent"]. "%"'
                     )
                )
                )); ?> 
