<?php
        $this->widget('ext.EExcelView', array(
            'dataProvider'=>$dataProvider
            ,'columns'=>array(
                array(
                    'name'=>'channel_id',
                    'header'=>'渠道',
                    'type'=>'raw',
                    'value'=>'$data["name"]'
                    ),
                array(
                    'header'=>'每日单价',
                    'type'=>'raw',
                    'value'=>'$data["now_cost"]'
                    ),
                array(
                    'header'=>'广告费用',
                    'type'=>'raw',
                    'value'=>'$data["cost"]'
                    ),
                array(
                    'header'=>'注册数',
                    'type'=>'raw',
                    'value'=>'$data["register"]'
                    ),
                array(
                        'header'=>'注册成本',
                        'type'=>'raw',
                        'value'=>'$data["cpa"]'
                     ),
                array(
                        'header'=>'回访用户数',
                        'type'=>'raw',
                        'value'=>'$data["revisit"]'
                     ),
                array(
                        'header'=>'回访率',
                        'type'=>'raw',
                        'value'=>'$data["revisitPercent"]."%"'
                     ),
                array(
                        'header'=>'回访成本',
                        'type'=>'raw',
                        'value'=>'$data["revisitCost"]'
                     ),
                array(
                        'header'=>'充值金额',
                        'type'=>'raw',
                        'value'=>'$data["payment"]'
                     ),
                array(
                        'header'=>'充值利润',
                        'type'=>'raw',
                        'value'=>'$data["income"]'
                     ),
                array(
                        'header'=>'回款率',
                        'type'=>'raw',
                        'value'=>'$data["profitPercent"]."%"'
                     )
                )
                ));?>
