<?php
        $this->widget('ext.EExcelView', array(
                            'dataProvider'=>$dataProvider
                           ,'columns'=>array(
                                array(
                                    'name'=>'game_id'
                                   ,'header'=>'游戏'
                                   ,'type'=>'raw'
                                   ,'value'=>'$data["game_name"]'
                                ),
                                array(
                                    'name'=>'server_id'
                                   ,'header'=>'区服'
                                   ,'type'=>'raw'
                                   ,'value'=>'$data["server_name"]'
                                    ),
                                array(
                                    'name'=>'channel_id'
                                   ,'header'=>'渠道'
                                   ,'type'=>'raw'
                                   ,'value'=>'$data["channel_name"]'
                                    ),
                                array(
                                     'header'=>'开服时间'
                                    ,'type'=>'raw'
                                    ,'value'=>'date("Y-m-d",$data["open_time"])'
                                    ),
                                array(
                                      'header'=>'平均游戏分成'
                                      ,'type'=>'raw'
                                      ,'value'=>'$data["share"]'
                                    ),
                                array(
                                      'header'=>'广告成本'
                                      ,'type'=>'raw'
                                      ,'value'=>'$data["cost"]'
                                     ),
                                array(
                                       'name'=>'register'
                                      ,'header'=>'注册数'
                                      ,'type'=>'raw'
                                      ,'value'=>'$data["register"]'
                                    ),
                                array(
                                       'name'=>'cpa'
                                      ,'header'=>'CPA'
                                      ,'type'=>'raw'
                                      ,'value'=>'$data["cpa"]'
                                    ),
                                array(
                                      'header'=>'回访人数'
                                      ,'type'=>'raw'
                                      ,'value'=>'$data["revisit"]'
                                    ),
                                array(
                                      'header'=>'回访率'
                                      ,'type'=>'raw'
                                      ,'value'=>'($data["register"]>0)?round($data["revisit"]*100/$data["register"],1)."%":"0%"'
                                    ),
                                array(
                                      'header'=>'回访成本'
                                      ,'type'=>'raw'
                                      ,'value'=>'($data["revisit"]>0)?round($data["cost"]/$data["revisit"],1):0'
                                    ),
                                array(
                                      'header'=>'累计开服天数'
                                      ,'type'=>'raw'
                                      ,'value'=>'ceil(( (time()-$data["open_time"])/86400))'
                                    ),
                                array(
                                      'header'=>'总利润'
                                      ,'type'=>'raw'
                                      ,'value'=>'$data["lifetime_income"]'
                                    ),
                                array(
                                      'header'=>'总回款率'
                                      ,'type'=>'raw'
                                      ,'value'=>'$data["lifetime_profit_percent"]."%"'
                                    ),
                                array(
                                      'header'=>'充值人数'
                                      ,'type'=>'raw'
                                      ,'value'=>'Server::getPaymentUser($data["server_id"],$data["channel_id"],$data["week"],$data["month"])'
                                    ),
                                array(
                                      'header'=>'付费率'
                                      ,'type'=>'raw'
                                      ,'value'=>'Server::getPaymentPercent($data["server_id"],$data["channel_id"],$data["mode"],$data["week"]?$data["week"]:$data["month"])."%"'
                                    ),
                                array(
                                      'header'=>'充值金额'
                                      ,'type'=>'raw'
                                      ,'value'=>'Server::getPaymentAmount($data["server_id"],$data["channel_id"],$data["week"],$data["month"])'
                                    ),
                                array(
                                      'header'=>'分成利润'
                                      ,'type'=>'raw'
                                      ,'value'=>'$data["current_income"]'
                                    ),
                               array(
                                      'name'=>'current_profit_percent'
                                     ,'header'=>'回款率'
                                     ,'type'=>'raw'
                                     ,'value'=>'$data["current_profit_percent"]."%"'
                                    ),
                                )
                )); ?> 
