 <?php
        $dataProvider->pagination=false;
        $this->widget('ext.EExcelView', array(
                            'dataProvider'=>$dataProvider
                           ,'columns'=>array(
                                array(
                                    'name'=>'method_name'
                                   ,'type'=>'raw'
                                   ,'header'=>'支付渠道'
                                ),
                                array(
                                    'name'=>'bank_name'
                                   ,'type'=>'raw'
                                   ,'header'=>'支付方式'
                                ),
                                array(
                                    'name'=>'payment_code'
                                   ,'type'=>'raw'
                                   ,'header'=>'充值code'
                                    ),
                                  array(
                                    'name'=>'paid_sum'
                                   ,'type'=>'raw'
                                   ,'header'=>'平台充值总额'
                                ),
                                array(
                                    'name'=>'payment_count'
                                   ,'type'=>'raw'
                                   ,'header'=>'充值订单数'
                                ),
                                array(
                                    'name'=>'tax_sum'
                                   ,'type'=>'raw'
                                   ,'header'=>'充值渠道费总额'
                                ),
                                array(
                                    'name'=>'bank_fee'
                                   ,'type'=>'raw'
                                   ,'header'=>'银行手续费'
                                ),
                                array(
                                    'name'=>'fee_adjustment'
                                   ,'type'=>'raw'
                                   ,'header'=>'手续费扣除差值'
                                )
                               )
                            ))
        ?> 
