 <?php
        $dataProvider->pagination=false;
        $this->widget('ext.EExcelView', array(
                            'dataProvider'=>$dataProvider
                           ,'columns'=>array(
                                array(
                                     'name'=>'platform_id'
                                    ,'type'=>'raw'
                                    ,'header'=>'平台订单号'
                                   ),
                                array(
                                    'name'=>'bussiness_id'
                                   ,'type'=>'raw'
                                   ,'header'=>'银行订单号'
                                   ,'value'=> '"\'". $data["bussiness_id"]'
                                ),
                                array(
                                    'name'=>'user_name'
                                   ,'type'=>'raw'
                                   ,'header'=>'账户'
                                ),
                                array(
                                    'name'=>'method_name'
                                   ,'type'=>'raw'
                                   ,'header'=>'支付方式'
                                   ,'value'=>'($data["payment_code"]=="")?$data["method_name"]."直冲":$data["method_name"].Payment::$bankList[$data["payment_code"]]'
                                ),
                                array(
                                    'name'=>'create_time'
                                   ,'type'=>'date'
                                   ,'header'=>'下单时间'
                                ),
                                array(
                                    'name'=>'game_name'
                                   ,'type'=>'raw'
                                   ,'header'=>'游戏'
                                ),
                                array(
                                    'name'=>'server_name'
                                   ,'type'=>'raw'
                                   ,'header'=>'区服'
                                ),
                                array(
                                    'name'=>'channel_id'
                                   ,'type'=>'raw'
                                   ,'header'=>'用户注册渠道'
                                   ,'value' => 'Channel::getName($data["channel_id"])'
                                ),
                                array(
                                    'name'=>'paid'
                                   ,'type'=>'raw'
                                   ,'header'=>'支付金额'
                                ),
                                array(
                                    'name'=>'payment_tax'
                                   ,'type'=>'raw'
                                   ,'header'=>'充值渠道费'
                                ),
                                array(
                                    'name'=>'real_paid'
                                   ,'type'=>'raw'
                                   ,'header'=>'游戏充值金额'
                                ),
                               )
                            ));
        ?> 
