 <?php
        $dataProvider->pagination=false;
        $this->widget('ext.EExcelView', array(
                            'dataProvider'=>$dataProvider
                           ,'columns'=>array(
                                array(
                                    'name'=>'create_time'
                                   ,'type'=>'date'
                                   ,'header'=>'下单时间'
                                ),
                                array(
                                    'name'=>'user_name'
                                   ,'type'=>'raw'
                                   ,'header'=>'帐号'
                                    ),
                                 array(
                                    'name'=>'channel_id'
                                   ,'type'=>'raw'
                                   ,'header'=>'用户注册渠道'
                                   ,'value' => 'Channel::getName($data["channel_id"])'
                                ),
                                array(
                                    'name'=>'game_name'
                                   ,'type'=>'raw'
                                   ,'header'=>'游戏'
                                ),
                                array(
                                    'name'=>'server_name'
                                   ,'type'=>'raw'
                                   ,'header'=>'区服'
                                ),
                                array(
                                    'name'=>'paid'
                                   ,'type'=>'raw'
                                   ,'header'=>'充值金额'
                                ),
                                array(
                                    'name'=>'register_time'
                                   ,'type'=>'date'
                                   ,'header'=>'注册时间'
                                ),
                                array(
                                    'header'=>'登录次数'
                                   ,'type'=>'number'
                                   ,'value'=>'UserServer::nbLoginTimes($data["user_id"],$data["server_id"])'
                                ),
                                array(
                                    'header'=>'充值次数'
                                   ,'type'=>'number'
                                   ,'value'=>'Order::nbUserOrder($data["user_id"],null,$data["server_id"])'
                                ),
                                array(
                                    'header'=>'充值总额'
                                   ,'type'=>'raw'
                                   ,'value'=>'Order::sumUserOrder($data["user_id"],null,$data["server_id"])'
                                ),
                                 array(
                                    'header'=>'平均充值'
                                   ,'type'=>'raw'
                                   ,'value'=>'round(Order::avgUserOrder($data["user_id"],null,$data["server_id"]),2)'
                                )
                               )
                            ))
        ?>
