 <?php
        $dataProvider->pagination=false;
        $this->widget('ext.EExcelView', array(
                            'dataProvider'=>$dataProvider
                           ,'columns'=>array(
                                array(
                                    'name'=>'id'
                                   ,'type'=>'raw'
                                   ,'header'=>'编号'
                                ),
                                array(
                                    'name'=>'game_name'
                                   ,'type'=>'raw'
                                   ,'header'=>'游戏'
                                ),
                                array(
                                    'name'=>'name'
                                   ,'type'=>'raw'
                                   ,'header'=>'区服'
                                ),
                                array(
                                    'name'=>'payment_user'
                                   ,'type'=>'raw'
                                   ,'header'=>'充值人数'
                                ),
                                array(
                                    'name'=>'payment_count'
                                   ,'type'=>'raw'
                                   ,'header'=>'充值订单数'
                                ),
                                array(
                                    'name'=>'paid_sum'
                                   ,'type'=>'raw'
                                   ,'header'=>'平台充值总额'
                                ),
                                array(
                                    'name'=>'tax_sum'
                                   ,'type'=>'raw'
                                   ,'header'=>'充值渠道费总额'
                                ),
                                array(
                                    'name'=>'real_paid'
                                   ,'type'=>'raw'
                                   ,'header'=>'游戏充值金额'
                                ),
                                array(
                                    'name'=>'share'
                                   ,'type'=>'raw'
                                   ,'header'=>'游戏分成比例'
                                ),
                                array(
                                    'name'=>'share_sum'
                                   ,'type'=>'raw'
                                   ,'header'=>'支付厂商总额'
                                )
                               )
                            ))
        ?>
